/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uvg_eats;

import clases.FoodCourtUVG;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.awt.Color;

/**
 *
 * @author javie
 */
public class SubMenuUsuario1 extends javax.swing.JFrame {
    String[] restaurantes;
    String[] restaurantesId;
    //Menu_Usuario menuPadre;
    /**
     * Creates new form Menu_Usuario
     */
    public SubMenuUsuario1() {
        initComponents();
        Color backGround= new Color(8,165,0);
        getContentPane().setBackground(backGround);
        String[] modelUsuario = {"1. Cliente", "2. Reparatidor", "3. Proveedor"};
        cBoxTUsuario.setModel(new javax.swing.DefaultComboBoxModel(modelUsuario));
        labelTipoCliente.setVisible(false);
        cBoxTCliente.setVisible(false);
        labelNivelAcceso.setVisible(false);
        txtNivAcceso.setVisible(false);
    }
    
    public void setRestaurantesDeMenu(String[] restaurantes, String[] restaurantesId){
        if(this.restaurantes != null){
            this.restaurantes = null;
        }
        if(this.restaurantesId != null){
            this.restaurantesId = null;
        }
        
        this.restaurantes = restaurantes;
        this.restaurantesId = restaurantesId;
        //System.out.println(restaurantesId);
        
        try{
            String[] array = FoodCourtUVG.getInstance().mostrarRestaurantesParaMenu().split(";");
            //String[] 
            /*for(String cosa : restaurantes){
                System.out.println(cosa);
            }*/ 
        }catch(Exception e){
            
        }
        
    }
    
    /*public void setMenuPadre(Menu_Usuario menuPadre){
        this.menuPadre = menuPadre;
    }*/
    
    /*public SubMenuUsuario1(){
        initComponents();
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        btn_aceptar = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_edad = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        cBoxTUsuario = new javax.swing.JComboBox<>();
        lbl7 = new javax.swing.JLabel();
        labelTipoCliente = new javax.swing.JLabel();
        cBoxTCliente = new javax.swing.JComboBox<>();
        labelNivelAcceso = new javax.swing.JLabel();
        txtNivAcceso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lbl1.setText("Ingrese sus datos para crear su usuario");

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl2.setText("ID");

        btn_aceptar.setBackground(new java.awt.Color(0, 255, 51));
        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 51, 51));
        btn2.setText("Salir");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        lbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl3.setText("Nombre");

        lbl4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl4.setText("Apellido");

        lbl5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl5.setText("Email");

        lbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl6.setText("Edad");

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });

        txt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edadActionPerformed(evt);
            }
        });

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        cBoxTUsuario.setBackground(new java.awt.Color(204, 255, 204));
        cBoxTUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cBoxTUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Cliente", "2. Repartidor", "3. Proveedor" }));
        cBoxTUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTUsuarioActionPerformed(evt);
            }
        });

        lbl7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl7.setText("Tipo de usuario");

        labelTipoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTipoCliente.setText("Tipo de cliente");

        cBoxTCliente.setBackground(new java.awt.Color(204, 255, 204));
        cBoxTCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cBoxTCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Estudiante", "2. Docente", "3. Personal administrativo" }));
        cBoxTCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTClienteActionPerformed(evt);
            }
        });

        labelNivelAcceso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNivelAcceso.setText("Nivel de acceso");

        txtNivAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNivAccesoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoUVG.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(57, 57, 57)
                                    .addComponent(cBoxTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(labelTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelNivelAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_edad)
                                        .addComponent(txt_email)
                                        .addComponent(txtNivAcceso)
                                        .addComponent(txt_nombre)
                                        .addComponent(txt_apellido)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cBoxTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_aceptar)
                                .addGap(84, 84, 84)
                                .addComponent(btn2)))
                        .addGap(174, 174, 174))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl7)
                    .addComponent(cBoxTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipoCliente)
                    .addComponent(cBoxTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNivelAcceso)
                    .addComponent(txtNivAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn2))
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        if(txt_id.getText().equals("") || txt_nombre.getText().equals("") || txt_apellido.getText().equals("") || txt_email.getText().equals("") || txt_edad.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Todos los campos deben estar llenos para continuar", "¡Alerta!", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(cBoxTUsuario.getSelectedIndex()== -1){
            JOptionPane.showMessageDialog(null,"Seleccione tipo tipo de cliente", "¡Alerta!", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(cBoxTUsuario.getSelectedIndex() == 0){
            int id = -1;
            int edad = -1;
            try{
                id = Integer.parseInt(txt_id.getText());
                edad = Integer.parseInt(txt_edad.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"El campo Id y Edad deben ser números enteros", "¡Error!", JOptionPane.INFORMATION_MESSAGE);
            }
            
            //System.out.println(cBoxTCliente.getSelectedIndex());
            if(cBoxTCliente.getSelectedIndex() == -1 || cBoxTCliente.getSelectedIndex() == 0){
                JOptionPane.showMessageDialog(null,"Debe seleccionar un tipo de cliente ha ingresar", "¡Alerta!", JOptionPane.INFORMATION_MESSAGE);
            }else{
                try{
                    FoodCourtUVG.getInstance().agregarCliente(id, txt_nombre.getText(), txt_apellido.getText(), txt_email.getText(), edad, cBoxTCliente.getSelectedItem().toString());
                    JOptionPane.showMessageDialog(null,"Cliente registrado exitosamente", "¡Exito!", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Ha ocurrido un error tratando de realizar la operación. Error.: " +e.toString(), "¡Error!", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
        }else if(cBoxTUsuario.getSelectedIndex() == 1){
            int id = -1;
            int edad = -1;
            try{
                id = Integer.parseInt(txt_id.getText());
                edad = Integer.parseInt(txt_edad.getText());
                
                try{
                    FoodCourtUVG.getInstance().agregarRepartidor(id, txt_nombre.getText(), txt_apellido.getText(), txt_email.getText(), edad);
                    JOptionPane.showMessageDialog(null,"Repartidor registrado correctamente", "¡Exito!", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"AQUII Ha ocurrido un error tratando de realizar la operación. Error: " + e.toString(), "¡Error!", JOptionPane.INFORMATION_MESSAGE);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"El campo Id y Edad deben ser números enteros", "¡Error!", JOptionPane.INFORMATION_MESSAGE);
            }
            
            
            
        }else if(cBoxTUsuario.getSelectedIndex() == 2){
           if(cBoxTCliente.getSelectedIndex()== -1){
                JOptionPane.showMessageDialog(null,"Seleccione un restaurante", "¡Alerta!", JOptionPane.INFORMATION_MESSAGE);
            }
           else if(cBoxTCliente.getSelectedItem().toString().equals("Aún no se han ingresado restaurantes")){
               
               JOptionPane.showMessageDialog(null,"Aún no existe ningún restaurante, primero debe crear uno.", "¡Alerta!", JOptionPane.INFORMATION_MESSAGE);
           }else{
               if(txtNivAcceso.getText().equals("")){
               JOptionPane.showMessageDialog(null,"Todos los campos deben estar llenos para continuar", "¡Alerta!", JOptionPane.INFORMATION_MESSAGE);
           }else{
                    int id = -1;
                    int edad = -1;
                    int nivAccess = -1;
                    try{
                        id = Integer.parseInt(txt_id.getText());
                        edad = Integer.parseInt(txt_edad.getText());
                        nivAccess = Integer.parseInt(txtNivAcceso.getText());
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,"El campo Id y Edad deben ser números enteros", "¡Error!", JOptionPane.INFORMATION_MESSAGE);
                    }

                    try{
                        int idIndex = cBoxTCliente.getSelectedIndex();
                        String rest = FoodCourtUVG.getInstance().nombreRestaurante(Integer.parseInt(restaurantesId[idIndex]));
                        if(rest == null){
                            JOptionPane.showMessageDialog(null,"No se ha encontrado el restaurante ingresado", "¡Error!", JOptionPane.INFORMATION_MESSAGE);
                        }else{
                           FoodCourtUVG.getInstance().agregarProveedor(id, txt_nombre.getText(), txt_apellido.getText(), txt_email.getText(), edad, rest, Integer.parseInt(restaurantesId[idIndex]), nivAccess);
                           JOptionPane.showMessageDialog(null,"Proveedor agregado exitosamente", "¡Exito!", JOptionPane.INFORMATION_MESSAGE);
                           dispose();
                        }

                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,"Ha ocurrido un error tratando de realizar la operación. Error: " + e.toString(), "¡Error!", JOptionPane.INFORMATION_MESSAGE);
                    }
               }
           }
           
           
            
        }
        
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void txt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edadActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void cBoxTClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTClienteActionPerformed
        int index = cBoxTCliente.getSelectedIndex();
        
        switch(index){
            case 0:
                
                break;
                
               
        }
    }//GEN-LAST:event_cBoxTClienteActionPerformed

    private void cBoxTUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTUsuarioActionPerformed
        int index = cBoxTUsuario.getSelectedIndex();
        System.out.println(index);
        switch(index){
            case 0:
                
                labelNivelAcceso.setVisible(false);
                txtNivAcceso.setVisible(false);
                String[] modelUsurio = {"Seleccionar" , "Estudiante", "Docente", "Personal administrativo"};
                cBoxTCliente.setModel(new javax.swing.DefaultComboBoxModel(modelUsurio));
                labelTipoCliente.setText("Tipo de cliente");
                
                labelTipoCliente.setVisible(true);
                cBoxTCliente.setVisible(true);
                break;
            
            case 1:
                labelTipoCliente.setVisible(false);
                cBoxTCliente.setVisible(false);
                labelNivelAcceso.setVisible(false);
                txtNivAcceso.setVisible(false);
                break;
                
            case 2:
                labelTipoCliente.setText("Restaurante donde trabaja");
                cBoxTCliente.setModel(new javax.swing.DefaultComboBoxModel(restaurantes));
                labelTipoCliente.setVisible(true);
                cBoxTCliente.setVisible(true);
                labelNivelAcceso.setVisible(true);
                txtNivAcceso.setVisible(true);
                break;
               
               
        }
    }//GEN-LAST:event_cBoxTUsuarioActionPerformed

    private void txtNivAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNivAccesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNivAccesoActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        dispose();
    }//GEN-LAST:event_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubMenuUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubMenuUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubMenuUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubMenuUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubMenuUsuario1().setVisible(true);
                
            }
        });
    }
    
    //@Override
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JComboBox<String> cBoxTCliente;
    private javax.swing.JComboBox<String> cBoxTUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelNivelAcceso;
    private javax.swing.JLabel labelTipoCliente;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JTextField txtNivAcceso;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
